when = [
    "today",
    "yesterday",
    "a few days ago",
    "at last week",
    "at this week",
    "at last month",
    "at this month",
    "at this winter",
    "at this spring",
    "at this summer",
    "at this fall",
    "right now",
    "30 days ago",
    "60 days ago",
    "70 days ago",
]
