problems = [
    "high taxes",
    "poor medicine",
    "bad education",
    "school violence",
    "car accidents",
    "abuse of office",
    "bad weather",
    "tap water",
    "computer games problem",
    "low taxes",
    "cold water",
    "hot water",
    "low salaries",
    "high salaries",
    "someone start business",
    "unknown blogger was poisoned",
    "some politician was killed",
    "nobody is vaccinated",
    "someone stole money from the cards",
    "the cops made a car accident",
    "flooded the entire region after the rains",
    "internet availability",
    "unemployment rise",
    "unemployment falls",
    "enemies are everywhere",
    "the forest is burning",
    "trains derailed",
    "special operation successfully failed",
    "the flagship was sunk from the shore",
    "someone attack the famous reporter",
    "there are no problems here",
    "default is close",
    "one more ship was sunk to the bottom",
    "the satanists attack the city",
    "the black mages attack the city",
    "the cannibals attack the city",
]
