problems = [
    "high taxes",
    "poor medicine",
    "bad education",
    "school violence",
    "car accidents",
    "abuse of office",
    "bad weather",
    "tap water",
    "computer games problem",
    "low taxes",
    "cold water",
    "hot water",
    "low salaries",
    "high salaries",
    "someone start business",
    "unknown blogger was poisoned",
    "some politician was killed",
    "nobody is vaccinated"
]