reporter = [
    "FOREIGN AGENT №1",
    "FOREIGN AGENT №2",
    "FOREIGN AGENT №3",
    "FOREIGN AGENT №4",
    "State Media",
    "Regional Media",
    "Republic Media",
    "Fastest News Media Inc",
    "Slowest News Media Inc",
    "Fast News Media Corp",
    "Slow News Media Corp",
    "Famous National Reporter",
    "Infamous Blogger",
]
