solutions = [
    "increase taxes",
    "build churches",
    "build a church",
    "increase taxes for small businesses",
    "decrease taxes",
    "protect Siberia",
    "the guilty will be punished",
    "the guilty will be found",
    "parents are guilty",
    "activists are guilty",
    "liberals are guilty",
    "youth are guilty",
    "youth liberals are guilty",
    "pupils are guilty",
    "pupils liberals are guilty",
    "the guilty are foreign agents",
    "the perpetrators are foreign agents",
    "enemies are guilty",
    "everybody have to be vaccinated",
    "build TikTok-houses",
    "nothing can be done",
    "a scooter drivers are guilty",
    "anime is a big problem",
    "need to edit Constitution",
    "VPN need to be blocked",
    "start resource mobilization",
    "ask the people to return back",
    "create greatest benefits for IT",
    "to late to think",
    "allow piracy",
]
