name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.dockerignore'
      - '.gitignore'
      - 'docker-compose.yaml'

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      get_current_tag: ${{ steps.set_current_tag_id.outputs.current_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "changelog.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.github_release.outputs.changelog }}

      - name: Set tag version to output
        id: set_current_tag_id
        run: echo "::set-output name=current_tag::${{ steps.tag_version.outputs.new_tag }}"

      - name: Step To run on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


  build:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: h0d0user/news_generator:latest

      - name: Step To run on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


  telegram:
    runs-on: ubuntu-latest
    name: Notification
    needs: [ release, build ]
    steps:

      - name: Notify in telegram after image was pushed
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>

            Commit with tag: ${{ needs.release.outputs.get_current_tag }}

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref }}

            <b>Pushed images:</b>
            <code>docker pull h0d0user/news_generator:latest</code>

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
